# Prepare Data

## Keytypes

```{r}
dirpath = '~/workstation/MetabSubtype/tasks/MultiOmics/results/20240930_essay_figures/metab/rna_pathway_heatmap/'
df.test_results=metab.test.results
df.test_results$ENSEMBL = rownames(edger.test.results)
colnames(df.test_results)[colnames(df.test_results) == "PValue"] ="pvalue"
colnames(df.test_results)[colnames(df.test_results) == "logFC"] ="log2fc"
# Map Different Names
tmp_key=bitr(df.test_results[['ENSEMBL']], #数据集
  fromType="ENSEMBL", #输入为SYMBOL格式
  toType="SYMBOL",  # 转为ENTERZID格式
  OrgDb="org.Hs.eg.db") #人类 数据库

matched_indices <- match(df.test_results$ENSEMBL, tmp_key$ENSEMBL)
df.test_results$SYMBOL <- tmp_key$SYMBOL[matched_indices]

tmp_key=bitr(df.test_results[['ENSEMBL']], #数据集
  fromType="ENSEMBL", #输入为SYMBOL格式
  toType="ENTREZID",  # 转为ENTERZID格式
  OrgDb="org.Hs.eg.db") #人类 数据库
matched_indices <- match(df.test_results$ENSEMBL, tmp_key$ENSEMBL)
df.test_results$ENTREZID <- tmp_key$ENTREZID[matched_indices]
df.test_results$is_sig = FALSE
df.test_results[df.test_results$pvalue <= 5e-2,'is_sig'] = TRUE

# write.csv(df.test_results,"~/workstation/MetabSubtype/tasks/MultiOmics/data/rna/metab_cluster_test_results.csv")
```

```{r}
# Update for Metab Test Results
dirpath = '~/workstation/MetabSubtype/tasks/MultiOmics/results/20240930_essay_figures/metab/rna_pathway_heatmap/'

# Metabolism test results
metab.test.results$ENSEMBL = rownames(edger.test.results)
colnames(metab.test.results)[colnames(metab.test.results) == "PValue"] ="pvalue"
colnames(metab.test.results)[colnames(metab.test.results) == "logFC"] ="log2fc"

# Map Different Names for Metabolism
tmp_key = bitr(metab.test.results[['ENSEMBL']],
  fromType="ENSEMBL", 
  toType="SYMBOL", 
  OrgDb="org.Hs.eg.db")

matched_indices <- match(metab.test.results$ENSEMBL, tmp_key$ENSEMBL)
metab.test.results$SYMBOL <- tmp_key$SYMBOL[matched_indices]

tmp_key = bitr(metab.test.results[['ENSEMBL']], 
  fromType="ENSEMBL", 
  toType="ENTREZID", 
  OrgDb="org.Hs.eg.db")
matched_indices <- match(metab.test.results$ENSEMBL, tmp_key$ENSEMBL)
metab.test.results$ENTREZID <- tmp_key$ENTREZID[matched_indices]

metab.test.results$is_sig = FALSE
metab.test.results[metab.test.results$pvalue <= 5e-2, 'is_sig'] = TRUE

# Update for Lipid Test Results
# Lipidomics test results
lipid.test.results$ENSEMBL = rownames(edger.test.results)
colnames(lipid.test.results)[colnames(lipid.test.results) == "PValue"] ="pvalue"
colnames(lipid.test.results)[colnames(lipid.test.results) == "logFC"] ="log2fc"

# Map Different Names for Lipidomics
tmp_key = bitr(lipid.test.results[['ENSEMBL']], 
  fromType="ENSEMBL", 
  toType="SYMBOL", 
  OrgDb="org.Hs.eg.db")

matched_indices <- match(lipid.test.results$ENSEMBL, tmp_key$ENSEMBL)
lipid.test.results$SYMBOL <- tmp_key$SYMBOL[matched_indices]

tmp_key = bitr(lipid.test.results[['ENSEMBL']], 
  fromType="ENSEMBL", 
  toType="ENTREZID", 
  OrgDb="org.Hs.eg.db")
matched_indices <- match(lipid.test.results$ENSEMBL, tmp_key$ENSEMBL)
lipid.test.results$ENTREZID <- tmp_key$ENTREZID[matched_indices]

lipid.test.results$is_sig = FALSE
lipid.test.results[lipid.test.results$pvalue <= 5e-2, 'is_sig'] = TRUE
```

```{r}
ENSG00000132915
v_corrected.edger[,'ENSG00000132915']

```

## Non-Coding

```{r}

# Patterns to match
patterns <- c('.+-P$', '.+-AS', '\\d{4,}', '^(MI|AC|LINC)', 'RNU-')
# 
# # Check if column matches any patterns
# keep.symbols <- character()
# length(df.test_results[['SYMBOL']])
# symbols=df.test_results[!is.na(df.test_results['SYMBOL']),'SYMBOL']
# pb=progress_bar$new(total=length(symbols))
# for (symbol in symbols) {
#   pb$tick()
#   if (!any(sapply(patterns, function(p) str_detect(symbol, p)))) {
#     keep.symbols <- c(keep.symbols, df.test_results[df.test_results$SYMBOL==symbol,'ENSEMBL'])
#   }
# }
# length(keep.symbols[!is.na(keep.symbols)])
# df.cpm.coding=df.cpm[,keep.symbols]
# dim(df.cpm.coding)
# keep.symbols=keep.symbols[!is.na(keep.symbols)]
# df.test_results$CODING=0
# df.test_results[df.test_results$ENSEMBL %in% keep.symbols,'CODING']=1
# 
# # write.csv(df.test_results,"~/workstation/MetabSubtype/tasks/MultiOmics/data/rna/rna_info.csv")
# rownames(df.test_results)=df.test_results$ENSEMBL
# df.test_results=merge(df.test_results,df.pathway_fc,by.x="ENSEMBL",by.y="row.names")
```

```{r}
library(stringr)

# Vectorized pattern detection
pattern_matches <- rowSums(sapply(patterns, function(p) str_detect(symbols, p))) == 0

# Subset the data based on the vectorized result
keep.symbols <- df.test_results[df.test_results$SYMBOL %in% symbols[pattern_matches], 'ENSEMBL']
length(keep.symbols)

df.test_results$CODING = 0
df.test_results[keep.symbols,'CODING'] = 1

metab.test.results$CODING = 0
metab.test.results[keep.symbols,'CODING'] = 1

lipid.test.results$CODING = 0
lipid.test.results[keep.symbols,'CODING'] = 1
```

```{r}


edger.test.results
```

## Lipid List

```{r}
filepath.lipid_genes='/home/suh/workstation/MetabSubtype/tasks/MultiOmics/data/lipid/GO_lipid metabolism related genes_log2_RPKM.csv'
df.lipid_genes = read.csv(filepath.lipid_genes,check.names = FALSE)

dim(df.lipid_genes)

dim(df.test_results[df.test_results$is_lipid,])
```

```{r}
genes.lipid = df.lipid_genes$GeneSymbol

df.test_results$is_lipid = toupper(df.test_results$SYMBOL) %in% toupper(genes.lipid) 

dim(df.test_results[df.test_results$is_lipid == TRUE,])

df.test_results[df.test_results$is_lipid == TRUE,]
```

# KEGG

```{r}


logfc_cutoff=log2(2)
pvalue_cutoff=5e-2
df.test_results$is_use=(df.test_results$pvalue<=pvalue_cutoff)&(abs(df.test_results$log2fc)>=logfc_cutoff)
entrezid.sig=df.test_results[df.test_results$is_use,'ENTREZID']
entrezid.sig=entrezid.sig[!is.na(entrezid.sig)]
length(entrezid.sig)

entrezid.lipid = df.test_results[df.test_results$is_lipid,'ENTREZID']
entrezid.lipid.sig=df.test_results[(df.test_results$is_use)&(df.test_results$is_lipid),'ENTREZID']

entrezid.universe=df.test_results[['ENTREZID']]
entrezid.universe=entrezid.universe[!is.na(entrezid.universe)]
length(entrezid.universe)

df.test_results.up=df.test_results[df.test_results$log2fc>0,]
entrezid.sig.up = df.test_results.up[df.test_results.up$is_use,'ENTREZID']
entrezid.sig.up=entrezid.sig.up[!is.na(entrezid.sig.up)]

df.test_results.down=df.test_results[df.test_results$log2fc<0,]
entrezid.sig.down = df.test_results.down[df.test_results.down$is_use,'ENTREZID']
entrezid.sig.down = entrezid.sig.down[!is.na(entrezid.sig.down)]

kegg_result=enrichKEGG(
  entrezid.sig,
  organism = "hsa",
  keyType = "kegg",
  pvalueCutoff = 0.05,
  pAdjustMethod = "BH",
  minGSSize = 1,
  maxGSSize = 500,
  qvalueCutoff = 0.2,
  universe = entrezid.universe,
  use_internal_data = FALSE
)
kegg_table <- na.omit(as.data.frame(kegg_result))

kegg_table$FoldEnrich <- apply(kegg_table, 1, 
                               function(x) as.numeric(unlist(strsplit(x[['GeneRatio']], '[/]'))[1])/
                                 as.numeric(unlist(strsplit(x[['GeneRatio']], '[/]'))[2])*
                                 as.numeric(unlist(strsplit(x[['BgRatio']], '[/]'))[2])/
                                 as.numeric(unlist(strsplit(x[['BgRatio']], '[/]'))[1]))
kegg_table$symbol=apply(kegg_table,1,get_symbols)

write.csv(df.test_results.up,"~/workstation/MetabSubtype/tasks/MultiOmics/results/lipid_up.csv")
write.csv(df.test_results.down,"~/workstation/MetabSubtype/tasks/MultiOmics/results/lipid_down.csv")
```

## Up

```{r}

kegg_result=enrichKEGG(
  entrezid.sig.up,
  organism = "hsa",
  keyType = "kegg",
  pvalueCutoff = 0.05,
  pAdjustMethod = "BH",
  minGSSize = 1,
  maxGSSize = 500,
  qvalueCutoff = 0.2,
  universe = entrezid.universe,
  use_internal_data = FALSE
)
kegg_table.up <- na.omit(as.data.frame(kegg_result))

kegg_table.up$FoldEnrich <- apply(kegg_table.up, 1, 
                               function(x) as.numeric(unlist(strsplit(x[['GeneRatio']], '[/]'))[1])/
                                 as.numeric(unlist(strsplit(x[['GeneRatio']], '[/]'))[2])*
                                 as.numeric(unlist(strsplit(x[['BgRatio']], '[/]'))[2])/
                                 as.numeric(unlist(strsplit(x[['BgRatio']], '[/]'))[1]))
kegg_table.up$symbol=apply(kegg_table.up,1,get_symbols)

kegg_table.up$comporison = 'II'
```

## Down

```{r}

kegg_result=enrichKEGG(
  entrezid.sig.down,
  organism = "hsa",
  keyType = "kegg",
  pvalueCutoff = 0.05,
  pAdjustMethod = "BH",
  minGSSize = 1,
  maxGSSize = 500,
  qvalueCutoff = 0.2,
  universe = entrezid.universe,
  use_internal_data = FALSE
)
kegg_table.down <- na.omit(as.data.frame(kegg_result))

kegg_table.down$FoldEnrich <- apply(kegg_table.down, 1, 
                               function(x) as.numeric(unlist(strsplit(x[['GeneRatio']], '[/]'))[1])/
                                 as.numeric(unlist(strsplit(x[['GeneRatio']], '[/]'))[2])*
                                 as.numeric(unlist(strsplit(x[['BgRatio']], '[/]'))[2])/
                                 as.numeric(unlist(strsplit(x[['BgRatio']], '[/]'))[1]))
kegg_table.down$symbol=apply(kegg_table.down,1,get_symbols)

kegg_table.down$comporison = 'I'
```

## Comporison

```{r}
unwanted_pathways = c()
kegg_table_draw = rbind(kegg_table.up,kegg_table.down)
# write.csv(kegg_table_draw,"~/workstation/MetabSubtype/tasks/MultiOmics/results/20240930_essay_figures/rna_lipid_kegg.csv")
kegg_table_draw=kegg_table_draw[!kegg_table_draw$Description %in% unwanted_pathways,]
names(kegg_table_draw)[names(kegg_table_draw) == "p.adjust"] <- "FDR"
p=ggplot(kegg_table_draw, aes(comporison, Description)) +
  geom_point(aes(fill = -log10(FDR), size = FoldEnrich), color = "black", shape = 21) +
  scale_y_discrete(limits = kegg_table_draw[['Description']])+
  scale_size(range = c(3, 13), breaks = c(seq(0,10,2))) +
  # scale_color_gradient(low="blue",high = "red")+
  scale_fill_viridis_c(option = "A", direction = -1, begin = 0.4, breaks = c(seq(2,8,2)))+
  #  scale_fill_viridis_c(option = "A", direction = -1, begin = 0.4, breaks = c(0.2,0.5, 1, 1.5)) +
  theme(plot.margin = margin(1, 1, 1, 1, "cm")) +
  # coord_fixed(ratio = 0.4) +
  labs(x = "-Log10(FDR)", y = "", title = "", 
       fill = "-Log10(FDR)", size = "Enrich Ratio") +
  theme(axis.text.x = element_text(size = 20, face = "plain", colour = "black",angle = 45,hjust = 1), 
        axis.text.y = element_text(size = 18, face = "plain", colour = "black")) +
  theme(legend.text = element_text(size = 10, face = "plain", colour = "black"), 
        legend.title = element_text(size = 10, face = "plain", colour = "black"), 
        legend.key.height = unit(0.3, "cm"), legend.key.width = unit(0.3, "cm"))
# pdf("~/workstation/MetabSubtype/tasks/MultiOmics/results/20240930_essay_figures/rna_lipid_I_II_upregulated.pdf",10,8)
print(p)
dev.off()
```

## Lipid Specific

```{r}


logfc_cutoff=log2(2)
pvalue_cutoff=5e-2
df.test_results$is_use=(df.test_results$pvalue<=pvalue_cutoff)&(abs(df.test_results$log2fc)>=logfc_cutoff)

entrezid.lipid = df.test_results[df.test_results$is_lipid,'ENTREZID']
entrezid.lipid.sig=df.test_results[(df.test_results$is_use)&(df.test_results$is_lipid),'ENTREZID']


kegg_result=enrichKEGG(
  entrezid.lipid.sig,
  organism = "hsa",
  keyType = "kegg",
  pvalueCutoff = 0.05,
  pAdjustMethod = "BH",
  minGSSize = 1,
  maxGSSize = 500,
  qvalueCutoff = 0.2,
  universe = entrezid.universe,
  use_internal_data = FALSE
)
kegg_table <- na.omit(as.data.frame(kegg_result))

kegg_table$FoldEnrich <- apply(kegg_table, 1, 
                               function(x) as.numeric(unlist(strsplit(x[['GeneRatio']], '[/]'))[1])/
                                 as.numeric(unlist(strsplit(x[['GeneRatio']], '[/]'))[2])*
                                 as.numeric(unlist(strsplit(x[['BgRatio']], '[/]'))[2])/
                                 as.numeric(unlist(strsplit(x[['BgRatio']], '[/]'))[1]))
kegg_table$symbol=apply(kegg_table,1,get_symbols)


```

### Up Down

```{r}

df.test_results.up=df.test_results[df.test_results$log2fc>0,]
# entrezid.sig.up = df.test_results.up[(df.test_results.up$is_lipid)&(df.test_results.up$is_use),'ENTREZID']
entrezid.sig.up = df.test_results.up[(df.test_results.up$is_lipid),'ENTREZID']
entrezid.sig.up = entrezid.sig.up[!is.na(entrezid.sig.up)]

df.test_results.down=df.test_results[df.test_results$log2fc<0,]
entrezid.sig.down = df.test_results.down[(df.test_results.down$is_lipid)&(df.test_results.down$is_use),'ENTREZID']
entrezid.sig.down = df.test_results.down[(df.test_results.down$is_lipid),'ENTREZID']
entrezid.sig.down = entrezid.sig.down[!is.na(entrezid.sig.down)]

length(entrezid.sig.up)
length(entrezid.sig.down)

# UP
kegg_result=enrichKEGG(
  entrezid.sig.up,
  organism = "hsa",
  keyType = "kegg",
  pvalueCutoff = 0.05,
  pAdjustMethod = "BH",
  minGSSize = 1,
  maxGSSize = 500,
  qvalueCutoff = 0.2,
  universe = entrezid.universe,
  use_internal_data = FALSE
)
kegg_table.up <- na.omit(as.data.frame(kegg_result))

kegg_table.up$FoldEnrich <- apply(kegg_table.up, 1, 
                               function(x) as.numeric(unlist(strsplit(x[['GeneRatio']], '[/]'))[1])/
                                 as.numeric(unlist(strsplit(x[['GeneRatio']], '[/]'))[2])*
                                 as.numeric(unlist(strsplit(x[['BgRatio']], '[/]'))[2])/
                                 as.numeric(unlist(strsplit(x[['BgRatio']], '[/]'))[1]))
kegg_table.up$symbol=apply(kegg_table.up,1,get_symbols)

kegg_table.up$comporison = 'II'

# DOWN
kegg_result=enrichKEGG(
  entrezid.sig.down,
  organism = "hsa",
  keyType = "kegg",
  pvalueCutoff = 0.05,
  pAdjustMethod = "BH",
  minGSSize = 1,
  maxGSSize = 500,
  qvalueCutoff = 0.2,
  universe = entrezid.universe,
  use_internal_data = FALSE
)
kegg_table.down <- na.omit(as.data.frame(kegg_result))

kegg_table.down$FoldEnrich <- apply(kegg_table.down, 1, 
                               function(x) as.numeric(unlist(strsplit(x[['GeneRatio']], '[/]'))[1])/
                                 as.numeric(unlist(strsplit(x[['GeneRatio']], '[/]'))[2])*
                                 as.numeric(unlist(strsplit(x[['BgRatio']], '[/]'))[2])/
                                 as.numeric(unlist(strsplit(x[['BgRatio']], '[/]'))[1]))
kegg_table.down$symbol=apply(kegg_table.down,1,get_symbols)

kegg_table.down$comporison = 'I'
```

```{r}
kegg_table.up[kegg_table.up$qvalue < 5e-2,]
kegg_table.down[kegg_table.down$qvalue < 5e-2,]
```

```{r}
write.csv(kegg_table_draw,"~/workstation/MetabSubtype/tasks/MultiOmics/results/20240930_essay_figures/rna_lipid_specific.csv")
kegg_table_draw = rbind(kegg_table.up,kegg_table.down)
kegg_table_draw = na.omit(kegg_table_draw)
kegg_table_draw = kegg_table_draw[!kegg_table_draw$Description %in% unwanted_pathways,]
kegg_table_draw = kegg_table_draw[order(kegg_table_draw$FoldEnrich,decreasing=TRUE),]
# kegg_table_draw = kegg_table_draw[1:10,]
names(kegg_table_draw)[names(kegg_table_draw) == "p.adjust"] <- "FDR"
p=ggplot(kegg_table_draw, aes(comporison, Description)) +
  geom_point(aes(fill = -log10(FDR), size = FoldEnrich), color = "black", shape = 21) +
  scale_y_discrete(limits = kegg_table_draw[['Description']])+
  scale_size(range = c(3, 13), breaks = c(seq(10,20,2))) +
  # scale_color_gradient(low="blue",high = "red")+
  scale_fill_viridis_c(option = "A", direction = -1, begin = 0.4, breaks = c(seq(1,50,10)))+
  #  scale_fill_viridis_c(option = "A", direction = -1, begin = 0.4, breaks = c(0.2,0.5, 1, 1.5)) +
  theme(plot.margin = margin(1, 1, 1, 1, "cm")) +
  # coord_fixed(ratio = 0.4) +
  labs(x = "-Log10(FDR)", y = "", title = "", 
       fill = "-Log10(FDR)", size = "Enrich Ratio") +
  theme(axis.text.x = element_text(size = 20, face = "plain", colour = "black",angle = 45,hjust = 1), 
        axis.text.y = element_text(size = 18, face = "plain", colour = "black")) +
  theme(legend.text = element_text(size = 10, face = "plain", colour = "black"), 
        legend.title = element_text(size = 10, face = "plain", colour = "black"), 
        legend.key.height = unit(0.3, "cm"), legend.key.width = unit(0.3, "cm"))

pdf("~/workstation/MetabSubtype/tasks/MultiOmics/results/20240930_essay_figures/kegg/rna_lipid_gene_specific_sig.pdf",10,5)
print(p)
dev.off()
```

# GSEA

```{r}


using.test_results=df.test_results
using.test_results$fc=2^(using.test_results$log2fc)
foldchanges=using.test_results[,"fc"]
names(foldchanges)=using.test_results[,'ENTREZID']
# gene_list<-na.omit(gene_list)
gene_list=foldchanges
gene_list = sort(gene_list, decreasing = TRUE)

length(gene_list)
length(unique(gene_list))
gene_list[duplicated(gene_list)]
kk2=gseKEGG(gene_list,organism = 'hsa',nPerm=1000,pvalueCutoff = 1)
length(gene_list)

df.kk2=as.data.frame(kk2)
df.kk2=df.kk2[order(-abs(df.kk2$enrichmentScore)),]
gseaplot(kk2, by = "runningScore", title = kk2$Description[1], geneSetID = 1)
head(kk2)

description_name="Regulation of lipolysis in adipocytes"
wanted_pathways=c('Regulation of lipolysis in adipocytes','Longevity regulating pathway','Type II diabetes mellitus')
for (description_name in wanted_pathways){
  p=gseaplot2(kk2,  title = description_name, geneSetID = which(kk2$Description==description_name))
  
  filepath_name=paste0('~/workstation/MetabSubtype/tasks/MultiOmics/results/20240930_essay_figures/gsea/metab/',description_name,'.pdf')
  pdf(filepath_name)
  print(p)
  dev.off()

}

```

# Mean Aggregate

```{r}

logfc_cutoff=log2(2)
pvalue_cutoff=5e-2
df.test_results$is_use=(df.test_results$pvalue<=pvalue_cutoff)&(abs(df.test_results$log2fc)>=logfc_cutoff)
entrezid.sig=df.test_results[df.test_results$is_use,'ENTREZID']
entrezid.sig=entrezid.sig[!is.na(entrezid.sig)]

kegg_result=enrichKEGG(
  na.omit(entrezid.sig),
  organism = "hsa",
  keyType = "kegg",
  pvalueCutoff = 1,
  pAdjustMethod = "BH",
  minGSSize = 1,
  maxGSSize = 1000,
  qvalueCutoff = 0.2,
  use_internal_data = FALSE
)
all.kegg_table <- na.omit(as.data.frame(kegg_result))

all.kegg_table$FoldEnrich <- apply(all.kegg_table, 1, 
                               function(x) as.numeric(unlist(strsplit(x[['GeneRatio']], '[/]'))[1])/
                                 as.numeric(unlist(strsplit(x[['GeneRatio']], '[/]'))[2])*
                                 as.numeric(unlist(strsplit(x[['BgRatio']], '[/]'))[2])/
                                 as.numeric(unlist(strsplit(x[['BgRatio']], '[/]'))[1]))
all.kegg_table$symbol=apply(all.kegg_table,1,get_symbols)
dim(all.kegg_table)
```

```{r}

##### Mean Aggregate #####  
dirpath="~/workstation/MetabSubtype/tasks/MultiOmics/results/20240930_essay_figures/rna_pathway_heatmap/"
# setwd(dirpath)
class_label='kmeans_2_clusters'
df.use_sample=df.sample

df.test_results$is_sig = df.test_results$pvalue<=5e-2

pvalue_cutoff=1
use_row_ha=FALSE
col_split=TRUE
pathway_names=unique(kegg_table$Description)
pathway_name=pathway_names[8]


for (pathway_name in pathway_names){
  # Get Pathway CPDs
    rnas <- unlist(strsplit(kegg_table[['geneID']], "[/]"))
    queries=df.test_results[match(rnas,df.test_results$ENTREZID),'SYMBOL']  
    row_ha=rowAnnotation(sig=df.test_results[df.test_results$SYMBOL %in% queries,'is_sig'],col=list(sig=c('TRUE'='yellow','FALSE'='white')))
  mat=as.matrix(df.test_results[df.test_results$SYMBOL %in% queries,'log2fc',drop=FALSE])
  rownames(mat)=df.test_results[match(rownames(mat),df.test_results$ENSEMBL),'SYMBOL']
  # mat=mat[order(mat),,drop=FALSE]
  mat=mat[order(rownames(mat)),'log2fc',drop=FALSE]
  bk=c(-3,0,3)
  col_fun<-colorRamp2(
    bk,
    c("#1D91C0", "white", "#E31A1C"))
  p=ComplexHeatmap::pheatmap(mat,
                           name = pathway_name,
                           cluster_cols = F,
                           cluster_rows = F,
                           cellheight = 10,
                           cellwidth = 40,
                           col = col_fun,
                           right_annotation=row_ha
                           # scale="col"
                           
  )
  # print(p)
  # Sys.sleep(3)
  pathway_name=str_replace_all(pathway_name,'/','_')
  pathway_name=str_replace_all(pathway_name,',','_')
  pathway_name=str_replace_all(pathway_name,'\\(','_')
  pathway_name=str_replace_all(pathway_name,'\\)','_')
  filepath=paste(dirpath,pathway_name,'.pdf',sep='')
  filepath=str_replace_all(filepath,'  ',' ')
  if (pathway_name=='Purine metabolism'){
    pdf(filepath,5,30)
  }else{
    pdf(filepath,5, 30)
  }
  draw(p)
  dev.off()

}

```

```{r}
df.test_results[df.test_results$ENSEMBL=='ENSG00000141959',]
na.omit(df.test_results[df.test_results$ENTREZID=='5211',])
```

## Manually Selected

```{r}
rnas.glycolysis.entrezid=c('5211','2821','2203','8789','226','5211','5212','5213')
rnas.cysteine=c('')

pathway_name='glycolysis'
rnas <- rnas.glycolysis
queries=df.test_results[match(rnas.glycolysis.entrezid,df.test_results$ENTREZID),'SYMBOL']  
row_ha=rowAnnotation(sig=df.test_results[df.test_results$SYMBOL %in% queries,'is_sig'],col=list(sig=c('TRUE'='yellow','FALSE'='white')))
mat=as.matrix(df.test_results[df.test_results$SYMBOL %in% queries,'log2fc',drop=FALSE])
rownames(mat)=df.test_results[match(rownames(mat),df.test_results$ENSEMBL),'SYMBOL']
# mat=mat[order(mat),,drop=FALSE]
bk=c(-1,0,1)
col_fun<-colorRamp2(
  bk,
  c("#1D91C0", "white", "#E31A1C"))
p=ComplexHeatmap::pheatmap(mat,
                         name = pathway_name,
                         cluster_cols = F,
                         cluster_rows = F,
                         cellheight = 10,
                         cellwidth = 40,
                         col = col_fun,
                         right_annotation=row_ha
                         # scale="col"
                         
)
# print(p)
# Sys.sleep(3)
pathway_name=str_replace_all(pathway_name,'/','_')
pathway_name=str_replace_all(pathway_name,',','_')
pathway_name=str_replace_all(pathway_name,'\\(','_')
pathway_name=str_replace_all(pathway_name,'\\)','_')
filepath=paste(dirpath,pathway_name,'.pdf',sep='')
filepath=str_replace_all(filepath,'  ',' ')
if (pathway_name=='Purine metabolism'){
  pdf(filepath,5,10)
}else{
  pdf(filepath,5, 5)
}
draw(p)
dev.off()
```

### Glycolysis

```{r}

pathway_name='glycolysis'
pathway_id <- "hsa00010"
# 获取通路信息
pathway_info <- keggGet(pathway_id)
# 提取基因信息
genes <- pathway_info[[1]]$GENE
# 将基因ID和名称分离
gene_ids <- genes[seq(1, length(genes), 2)]
gene_names <- genes[seq(2, length(genes), 2)]

# Filter
rnas <- df.test_results[abs(df.test_results$log2fc)>log2(1.2)&(df.test_results$pvalue<5e-2)&(df.test_results$ENTREZID %in% gene_ids),'ENTREZID']

queries=df.test_results[match(rnas,df.test_results$ENTREZID),'SYMBOL']  
row_ha=rowAnnotation(sig=df.test_results[df.test_results$SYMBOL %in% queries,'is_sig'],col=list(sig=c('TRUE'='yellow','FALSE'='white')))
mat=as.matrix(df.test_results[df.test_results$SYMBOL %in% queries,'log2fc',drop=FALSE])
rownames(mat)=df.test_results[match(rownames(mat),df.test_results$ENSEMBL),'SYMBOL']
# mat=mat[order(mat),,drop=FALSE]
bk=c(-1.5,0,1.5)
col_fun<-colorRamp2(
  bk,
  c("#1D91C0", "white", "#E31A1C"))
p=ComplexHeatmap::pheatmap(mat,
                         name = pathway_name,
                         cluster_cols = F,
                         cluster_rows = F,
                         cellheight = 10,
                         cellwidth = 40,
                         col = col_fun,
                         right_annotation=row_ha
                         # scale="col"
                         
)
# print(p)
# Sys.sleep(3)
pathway_name=str_replace_all(pathway_name,'/','_')
pathway_name=str_replace_all(pathway_name,',','_')
pathway_name=str_replace_all(pathway_name,'\\(','_')
pathway_name=str_replace_all(pathway_name,'\\)','_')
filepath=paste(dirpath,pathway_name,'.pdf',sep='')
filepath=str_replace_all(filepath,'  ',' ')
if (pathway_name=='Purine metabolism'){
  pdf(filepath,5,10)
}else{
  pdf(filepath,5, 5)
}
draw(p)
dev.off()
df.test_results[df.test_results$ENTREZID %in% rnas,c('log2fc','SYMBOL','ENTREZID')]
```

### Pentose

```{r}

pathway_name='pentose'
pathway_id <- "hsa00030"
# 获取通路信息
pathway_info <- keggGet(pathway_id)
# 提取基因信息
genes <- pathway_info[[1]]$GENE
# 将基因ID和名称分离
gene_ids <- genes[seq(1, length(genes), 2)]
gene_names <- genes[seq(2, length(genes), 2)]

# Filter
rnas <- df.test_results[abs(df.test_results$log2fc)>log2(1.2)&(df.test_results$pvalue<5e-2)&(df.test_results$ENTREZID %in% gene_ids),'ENTREZID']

queries=df.test_results[match(rnas,df.test_results$ENTREZID),'SYMBOL']  
row_ha=rowAnnotation(sig=df.test_results[df.test_results$SYMBOL %in% queries,'is_sig'],col=list(sig=c('TRUE'='yellow','FALSE'='white')))
mat=as.matrix(df.test_results[df.test_results$SYMBOL %in% queries,'log2fc',drop=FALSE])
rownames(mat)=df.test_results[match(rownames(mat),df.test_results$ENSEMBL),'SYMBOL']
# mat=mat[order(mat),,drop=FALSE]
bk=c(-1.5,0,1.5)
col_fun<-colorRamp2(
  bk,
  c("#1D91C0", "white", "#E31A1C"))
p=ComplexHeatmap::pheatmap(mat,
                         name = pathway_name,
                         cluster_cols = F,
                         cluster_rows = F,
                         cellheight = 10,
                         cellwidth = 40,
                         col = col_fun,
                         right_annotation=row_ha
                         # scale="col"
                         
)
# print(p)
# Sys.sleep(3)
pathway_name=str_replace_all(pathway_name,'/','_')
pathway_name=str_replace_all(pathway_name,',','_')
pathway_name=str_replace_all(pathway_name,'\\(','_')
pathway_name=str_replace_all(pathway_name,'\\)','_')
filepath=paste(dirpath,pathway_name,'.pdf',sep='')
filepath=str_replace_all(filepath,'  ',' ')
if (pathway_name=='Purine metabolism'){
  pdf(filepath,5,10)
}else{
  pdf(filepath,5, 5)
}
draw(p)
dev.off()
df.test_results[df.test_results$ENTREZID %in% rnas,]
```

### Methionine

```{r}

pathway_name='methionine'
pathway_id <- "hsa00270"
# 获取通路信息
pathway_info <- keggGet(pathway_id)
# 提取基因信息
genes <- pathway_info[[1]]$GENE
# 将基因ID和名称分离
gene_ids <- genes[seq(1, length(genes), 2)]
gene_names <- genes[seq(2, length(genes), 2)]

df.test_results[df.test_results$ENTREZID %in% gene_ids,]
# Filter
rnas <- df.test_results[abs(df.test_results$log2fc)>log2(1)&(df.test_results$pvalue<5)&(df.test_results$ENTREZID %in% gene_ids),'ENTREZID']

queries=df.test_results[match(rnas,df.test_results$ENTREZID),'SYMBOL']  
row_ha=rowAnnotation(sig=df.test_results[df.test_results$SYMBOL %in% queries,'is_sig'],col=list(sig=c('TRUE'='yellow','FALSE'='white')))
df.test_results = df.test_results[order(df.test_results$SYMBOL),]

mat=as.matrix(df.test_results[df.test_results$SYMBOL %in% queries,'log2fc',drop=FALSE])
rownames(mat)=df.test_results[match(rownames(mat),df.test_results$ENSEMBL),'SYMBOL']
# mat=mat[order(mat),,drop=FALSE]
bk=c(-2,0,2)
col_fun<-colorRamp2(
  bk,
  c("#1D91C0", "white", "#E31A1C"))
p=ComplexHeatmap::pheatmap(mat,
                         name = pathway_name,
                         cluster_cols = F,
                         cluster_rows = F,
                         cellheight = 10,
                         cellwidth = 40,
                         col = col_fun,
                         right_annotation=row_ha
                         # scale="col"
                         
)
# Sys.sleep(3)
pathway_name=str_replace_all(pathway_name,'/','_')
pathway_name=str_replace_all(pathway_name,',','_')
pathway_name=str_replace_all(pathway_name,'\\(','_')
pathway_name=str_replace_all(pathway_name,'\\)','_')
filepath=paste(dirpath,pathway_name,'.pdf',sep='')
filepath=str_replace_all(filepath,'  ',' ')
if (pathway_name=='Purine metabolism'){
  pdf(filepath,5,10)
}else{
  pdf(filepath,5, 10)
}
draw(p)
dev.off()
df.test_results = df.test_results[order(df.test_results$SYMBOL),]
df.test_results[df.test_results$ENTREZID %in% rnas,c('log2fc','SYMBOL','ENTREZID')]

```

### Purine

```{r}


pathway_name='purine'
pathway_id <- "hsa00230"
# 获取通路信息
pathway_info <- keggGet(pathway_id)
# 提取基因信息
genes <- pathway_info[[1]]$GENE
# 将基因ID和名称分离
gene_ids <- genes[seq(1, length(genes), 2)]
gene_names <- genes[seq(2, length(genes), 2)]

# Filter
rnas <- df.test_results[abs(df.test_results$log2fc)>log2(1)&(df.test_results$pvalue<5)&(df.test_results$ENTREZID %in% gene_ids),'ENTREZID']

# No Filter

rnas = df.test_results[df.test_results$ENTREZID %in% gene_ids,'ENTREZID']


queries=df.test_results[match(rnas,df.test_results$ENTREZID),'SYMBOL']  
row_ha=rowAnnotation(sig=df.test_results[df.test_results$SYMBOL %in% queries,'is_sig'],col=list(sig=c('TRUE'='yellow','FALSE'='white')))
mat=as.matrix(df.test_results[df.test_results$SYMBOL %in% queries,'log2fc',drop=FALSE])
rownames(mat)=df.test_results[match(rownames(mat),df.test_results$ENSEMBL),'SYMBOL']
# mat=mat[order(mat),,drop=FALSE]
bk=c(-1.5,0,1.5)
col_fun<-colorRamp2(
  bk,
  c("#1D91C0", "white", "#E31A1C"))
p=ComplexHeatmap::pheatmap(mat,
                         name = pathway_name,
                         cluster_cols = F,
                         cluster_rows = F,
                         cellheight = 10,
                         cellwidth = 40,
                         col = col_fun,
                         right_annotation=row_ha
                         # scale="col"
                         
)
# print(p)
# Sys.sleep(3)
pathway_name=str_replace_all(pathway_name,'/','_')
pathway_name=str_replace_all(pathway_name,',','_')
pathway_name=str_replace_all(pathway_name,'\\(','_')
pathway_name=str_replace_all(pathway_name,'\\)','_')
filepath=paste(dirpath,pathway_name,'.pdf',sep='')
filepath=str_replace_all(filepath,'  ',' ')
if (pathway_name=='Purine metabolism'){
  pdf(filepath,5,25)
}else{
  pdf(filepath,5, 5)
}
draw(p)
dev.off()
df.test_results[df.test_results$ENTREZID %in% rnas,]
df.test_results[df.test_results$ENTREZID %in% rnas,c('SYMBOL','ENTREZID','ENSEMBL')]
```

## Heatmap

```{r}

rnas.glycolysis.ensembl=df.test_results[match(rnas.glycolysis.entrezid,df.test_results$ENTREZID),'ENSEMBL']
rnas.glycolysis.symbol=df.test_results[match(rnas.glycolysis.entrezid,df.test_results$ENTREZID),'SYMBOL']

target_cols=rnas.glycolysis.ensembl
target_cols.symbol=rnas.glycolysis.symbol
class_label='kmeans_2_clusters'
df.sample_cluster$kmeans_2_clusters=as.factor(df.sample_cluster[['kmeans_2_clusters']])
loaddata=merge(v_corrected.edger,df.cluster_result[,class_label,drop=FALSE],by="row.names")
rownames(loaddata)=loaddata[,1]
loaddata=loaddata[2:ncol(loaddata)]
loaddata=loaddata[,c(target_cols,class_label)]
colnames(loaddata)=c(df.test_results[match(colnames(loaddata)[1:(ncol(loaddata)-1)],df.test_results$ENSEMBL),'SYMBOL'],class_label)
loaddata[idx]=0
draw_heatmap(loaddata[!is.na(loaddata[class_label]),],target_cols.symbol,class_label,class_label,FALSE)
```

```{r}
df.test_results[rnas.glycolysis.ensembl,]
```

```{r}

wilcox.test(loaddata[['']] ~ loaddata[,class_label], data = df.test, exact = FALSE)

```

## Volcano

```{r}

dim(df.test_results[abs(df.test_results$log2fc)>1 & (df.test_results$pvalue<5e-2) ,])
queries=df.test_results[abs(df.test_results$log2fc)>1 & (df.test_results$pvalue<5e-2),'SYMBOL'] 
length(queries)

# Metab
volcano.test_results=metab.test.results
volcano.test_results$fc = 2^(volcano.test_results$log2fc)
colnames(volcano.test_results)[colnames(volcano.test_results) == "fc"] ="FC"
colnames(volcano.test_results)[colnames(volcano.test_results) == "log2fc"] ="log2FC"
colnames(volcano.test_results)[colnames(volcano.test_results) == "SYMBOL"] ="Metabolites"

volcano.test_results=volcano.test_results[volcano.test_results$Metabolites %in% queries,]
rownames(volcano.test_results)=volcano.test_results$SYMBOL
pdf("~/workstation/MetabSubtype/tasks/MultiOmics/results/20240930_essay_figures/Immune/metab_volcano.pdf")
draw_volcano(volcano.test_results,0.05,2,'Metabolites')
dev.off()

# Lipid
volcano.test_results=lipid.test.results
volcano.test_results$fc = 2^(volcano.test_results$log2fc)
colnames(volcano.test_results)[colnames(volcano.test_results) == "fc"] ="FC"
colnames(volcano.test_results)[colnames(volcano.test_results) == "log2fc"] ="log2FC"
colnames(volcano.test_results)[colnames(volcano.test_results) == "SYMBOL"] ="Metabolites"

volcano.test_results=volcano.test_results[volcano.test_results$Metabolites %in% queries,]
rownames(volcano.test_results)=volcano.test_results$SYMBOL

pdf("~/workstation/MetabSubtype/tasks/MultiOmics/results/20240930_essay_figures/Immune/lipid_volcano.pdf")
draw_volcano(volcano.test_results,0.05,2,'Lipids')
dev.off()
```

```{r}
df.test_results = lipid.test.results
pathway_name='Regulation of lipolysis in adipocytes'
# 指定目标KEGG通路，例如hsa04110（自噬通路）
pathway_id <- "hsa04923"
# 获取通路信息
pathway_info <- keggGet(pathway_id)
# 提取基因信息
genes <- pathway_info[[1]]$GENE
# 将基因ID和名称分离
gene_ids <- genes[seq(1, length(genes), 2)]
gene_names <- genes[seq(2, length(genes), 2)]

queries=df.test_results[match(gene_ids,df.test_results$ENTREZID),'SYMBOL'] 

volcano.test_results=df.test_results
volcano.test_results$fc = 2^(volcano.test_results$log2fc)
colnames(volcano.test_results)[colnames(volcano.test_results) == "fc"] ="FC"
colnames(volcano.test_results)[colnames(volcano.test_results) == "log2fc"] ="log2FC"

colnames(volcano.test_results)[colnames(volcano.test_results) == "SYMBOL"] ="Metabolites"

volcano.test_results=volcano.test_results[volcano.test_results$Metabolites %in% queries,]
rownames(volcano.test_results)=volcano.test_results$SYMBOL

draw_volcano(volcano.test_results,0.05,2,'Lipid Regulation of lipolysis in adipocytes')
```

```{r}
volcano.test_results <- volcano.test_results[order(-abs(volcano.test_results$log2FC),volcano.test_results$pvalue), ]
volcano.test_results[1:20,c('ENTREZID','Metabolites')]
```

# Cell Type

```{r}

# https://www.sciencedirect.com/science/article/pii/S0092867423013351?via%3Dihub
# Marker genes for each cell type
Tcell <- c("CD40LG", "TBX21", "SH2D1A", "PHYPIN", "ZNF831", "CD6", "THEMIS", "UBASH3A", "TRA1", "EOMES", 
           "GRAP2", "ZAP70", "SIRPG", "ICOS", "FASLG", "CD8A", "CD8B", "ITK", "GZMA", "KLRK1", "GZMH", 
           "GZMK", "CD3D", "CD3E", "CD3G", "SIGLEC7", "MS4A4A", "SIGLEC1", "CD300E")

Myeloid <- c("CLEC10A", "CD14", "CD16", "VSIG4", "CD33", "MS4A7", "LY6", "CLEC5A", "FCER1A", "LILRB2", 
             "CSF1R", "LILRA1", "ADORA3", "MPEG1", "FCN1", "RNASE6", "FPR3", "CYBB", "MS4A4E", "OLR1", 
             "CD163", "WDFY4", "LAG3", "CRIM1", "NAAA", "GRIK4", "PSMB9", "SERP2", "HOXB4", "CASP7", 
             "TMCC2", "ARPC5L", "MCTP2", "LYST")

Stroma <- c("CDH11", "DCN", "PDGFRA", "COL1A2", "ISLR", "COL1A1", "COL14A1", "BGN", "COL5A2", "POSTN", 
            "PODH18", "ADAMTS12", "MXRA5", "SULF1", "EDNRA", "PRRX1", "COL3A1", "THY1", "LUM", "COL12A1", 
            "COL14A2")

Treg <- c("FOXP3", "IL2RA", "CD80", "CD17", "LAIR2", "CCR8", "CCL22", "TNFRSF18", "TNFRSF4", "DSC1", "SESN1")

CD4 <- c("BACH2", "TRABD2A", "IL7R", "HDAC4", "NR3C2", "APOBEC3", "PABPC1", "HLA-DPB1", "MFHAS1", "SELL")

CD8 <- c("FASLG", "CD8A", "SETBP1", "CTSW", "APOBEC3C", "BTNL8", "ULBP3", "RAD51", "WNT9A", "CER55", 
         "NK67", "FAM156A", "ZNF696", "MCF5", "DPF3", "TTC24", "YARS", "EBP", "TRPS1", "GZMH", "VCAM1")

cDC2 <- c("FCER1A", "CD1C", "XCR1", "CLEC10A", "BATF3")

cDC1 <- c("IDO1", "C1orf54", "TREM2")

Macrophage <- c("APOE", "TREM2", "CIQB", "CLEC9A", "VSIG4")

ClassicalMonocytes <- c("S100A8", "S100A9", "VCAN", "FCN1", "LYZ")
```

```{r}
# Function to convert gene SYMBOLs to ENSEMBL IDs
convert_to_ensembl <- function(cell_markers, conversion_df) {
  # cell_markers: A named list of cell type gene vectors
  # conversion_df: A dataframe with SYMBOL and ENSEMBL columns
  
  # Initialize an empty list for converted ENSEMBL IDs
  cell_markers_ensembl <- list()
  
  # Loop through each cell type
  for (cell_type in names(cell_markers)) {
    # Get current SYMBOL gene list
    gene_symbols <- cell_markers[[cell_type]]
    
    # Filter conversion dataframe to match SYMBOLs
    matched_genes <- conversion_df[conversion_df$SYMBOL %in% gene_symbols, ]
    
    # Extract ENSEMBL IDs
    ensembl_ids <- matched_genes$ENSEMBL
    
    # Store the ENSEMBL IDs in the output list
    cell_markers_ensembl[[cell_type]] <- unique(ensembl_ids)
  }
  
  return(cell_markers_ensembl)
}

# Example usage:
# Assuming df.test_results is your dataframe with SYMBOL and ENSEMBL columns
# And cell_markers is the list of cell type gene SYMBOLs

# Convert SYMBOL cell markers to ENSEMBL IDs

# Print the resulting list of ENSEMBL IDs
cell_markers <- list(
  Tcell = Tcell,
  Myeloid = Myeloid,
  Stroma = Stroma,
  Treg = Treg,
  CD4 = CD4,
  CD8 = CD8,
  cDC2 = cDC2,
  cDC1 = cDC1,
  Macrophage = Macrophage,
  ClassicalMonocytes = ClassicalMonocytes
)
cell_markers_ensembl <- convert_to_ensembl(cell_markers, df.test_results)

for (cell_type in names(cell_markers)) {
    # Get current SYMBOL gene list
    gene_symbols <- cell_markers[[cell_type]]
    print(paste(cell_type,length(gene_symbols)))
}
for (cell_type in names(cell_markers_ensembl)) {
    # Get current SYMBOL gene list
    gene_symbols <- cell_markers[[cell_type]]
    print(paste(cell_type,length(gene_symbols)))
}
```

```{r}
# Function to calculate average marker expression per cell type
calculate_cell_type_average <- function(rna_data, cell_markers) {
  # rna_data: A dataframe with samples as rows and genes as columns
  # cell_markers: A named list of cell type markers
  
  averages <- data.frame(row.names = rownames(rna_data))
  
  for (cell_type in names(cell_markers)) {
    # Extract marker genes that exist in the RNA dataframe
    valid_markers <- cell_markers[[cell_type]][cell_markers[[cell_type]] %in% colnames(rna_data)]
    
    if (length(valid_markers) > 0) {
      # Calculate the average expression for the valid marker genes
      averages[[cell_type]] <- rowMeans(rna_data[, valid_markers, drop = FALSE])
    } else {
      # If no valid markers, fill with NA
      averages[[cell_type]] <- NA
    }
  }
  
  return(averages)
}

df.cell_type = calculate_cell_type_average(v_corrected.edger,cell_markers_ensembl)
# Example usage:
# Define a list of cell markers


# Assuming 'rna_data' is your RNA dataframe
# result <- calculate_cell_type_average(rna_data, cell_markers)
```

## Heatmap

```{r}
dirpath = '~/workstation/MetabSubtype/tasks/MultiOmics/results/20240930_essay_figures/Immune/'
class_label = 'lipid_cluster'
ha_col = class_label
loaddata = merge(df.cell_type,df.sample[,c(class_label),drop = FALSE],by="row.names")
rownames(loaddata) = loaddata[[1]]
loaddata = loaddata[,2:ncol(loaddata)]

candidate_colors <- c("#8ea3c2",  "#8ccdbf", "#edb17f",  "#f1df82","#FEA3A2","#8E8BFE")

df.ha = loaddata[,c(class_label),drop = FALSE]
ha_color_mapping=c()
ha_color_mapping=candidate_colors[1:length(unique(df.ha[[ha_col]]))]
ha_color_mapping= setNames(ha_color_mapping,unique(df.ha[[ha_col]]))
color_list=NULL
color_list[[ha_col]]=ha_color_mapping

top_ha = HeatmapAnnotation(df=df.ha,col = color_list,
        simple_anno_size=unit(4, "mm"),
        #border = T,
        gap = unit(1, "points"),
        show_annotation_name = TRUE)
    col_ha=df.label_col
bk=c(-1.5,0,1.5)
col_fun<-colorRamp2(
    bk,
    c("#1D91C0", "white", "#E31A1C"))
mat = t(data.matrix(loaddata[,1:ncol(df.cell_type)]))
col_ha = loaddata[class_label]
p = ComplexHeatmap::pheatmap(mat,
                        col = col_fun,
                        name = "Relative level",
                        top_annotation = top_ha,
                        column_split = col_ha,
                        cluster_row_slices=F,
                        fontsize_row = 7, 
                        cluster_cols = T,
                        row_title_rot = 0,
                        fontsize_col = 5,
                        treeheight_row = 20,
                        treeheight_col = 20,
                        row_title_gp = gpar(fontsize = 7),
                        legend_breaks=seq(break_low_boundary,break_high_boundary,(break_high_boundary-break_low_boundary)/4),
                        scale="row"
                    )

filepath = paste0(dirpath,class_label,'_cellType.pdf')
pdf(filepath,8,3)
print(p)
dev.off()
```

# Stacked Bar

```{r}

# Function for stacked bar chart with percentage distribution (handling NAs)
plot_stacked_bar_percentage <- function(df, cluster_col, attribute_col,order_attribute = NULL) {
    df= df [,2:ncol(df)]

  # Replace NA values with a label (e.g., "Unknown") in the attribute column
  # df[[attribute_col]] <- ifelse(is.na(df[[attribute_col]]), "Unknown", df[[attribute_col]])
    df = df[!is.na(df[[attribute_col]]),]
    df = df[!is.na(df[[cluster_col]]),]

    df = df[order(df[[attribute_col]]),]
    df[[cluster_col]] <- factor(df[[cluster_col]], levels = c(1,2))

    if (!is.null(order_attribute)) {
    df[[attribute_col]] <- factor(df[[attribute_col]], levels = order_attribute,ordered= TRUE)
  } else {
    df[[attribute_col]] <- factor(df[[attribute_col]], levels = unique(df[[attribute_col]]),ordered= TRUE)
  }
  
  # Convert cluster column to factor for discrete x-axis with desired order
  
  
  # Calculate the percentage distribution within each cluster
  df_summary <- df %>%
    group_by(.data[[cluster_col]], .data[[attribute_col]]) %>%
    tally() %>%
    group_by(.data[[cluster_col]]) %>%
    mutate(percentage = n / sum(n) * 100)
  
  # Create a dynamic color palette based on unique attribute values
  color_palette <- scales::hue_pal()(length(unique(df[[attribute_col]])))
  
  # Plot the stacked bar with percentage distribution
  p=ggplot(df_summary, aes_string(x = cluster_col, y = "percentage", fill = attribute_col)) +
    geom_bar(stat = "identity",width=0.4) +
    scale_fill_manual(values = color_palette) +  # Use dynamic color palette
    scale_y_continuous(labels = scales::percent_format(scale = 1)) +
    labs(x = "Clusters", y = "Percentage", title = "Stacked Bar - Percentage Distribution") +
    ggtitle(cluster_col)+
    theme_minimal()+
    theme(
    # axis.text.x = element_text(angle = 0, hjust = 1),  # Rotate x-axis labels if needed
    aspect.ratio = 0.6  # Adjust the aspect ratio to make the plot thinner
    )
  return(p)
}

# Function for stacked bar chart with absolute numbers (handling NAs)
plot_stacked_bar_absolute <- function(df, cluster_col, attribute_col) {
    df= df [,2:ncol(df)]

  # Replace NA values with a label (e.g., "Unknown") in the attribute column
  # df[[attribute_col]] <- ifelse(is.na(df[[attribute_col]]), "Unknown", df[[attribute_col]])
  df = df[!is.na(df[[attribute_col]]),]
  # Ensure the attribute column is a factor
  df[[attribute_col]] <- factor(df[[attribute_col]], levels = unique(df[[attribute_col]]))
  
  # Convert cluster column to factor for discrete x-axis
  df[[cluster_col]] <- factor(df[[cluster_col]], levels = unique(df[[cluster_col]]))
  
  # Calculate the absolute numbers within each cluster
  df_summary <- df %>%
    group_by(.data[[cluster_col]], .data[[attribute_col]]) %>%
    tally()
  
  # Create a dynamic color palette based on unique attribute values
  color_palette <- scales::hue_pal()(length(unique(df[[attribute_col]])))
  
  # Plot the stacked bar with absolute numbers
  p=ggplot(df_summary, aes_string(x = cluster_col, y = "n", fill = attribute_col)) +
    geom_bar(stat = "identity",width=0.4) +
    scale_fill_manual(values = color_palette) +  # Use dynamic color palette
    labs(x = "Clusters", y = "Count", title = "Stacked Bar - Absolute Numbers") +
    theme_minimal()+
    ggtitle(cluster_col)+
    theme(
    # axis.text.x = element_text(angle = 0, hjust = 1),  # Rotate x-axis labels if needed
    aspect.ratio = 0.6  # Adjust the aspect ratio to make the plot thinner
    )
  return(p)
}
```

```{r}

df.sample
stacked.sample = df.sample
stacked.sample$smoke = ifelse(is.na(df.sample$smoke),'NA',ifelse(df.sample$smoke=='是','Yes','No'))
stacked.sample$survival_level = ifelse(df.sample$os>24,'>24 months','0-24 months')
stacked.sample$subtype = ifelse(is.na(df.sample['病理类型']),'NA',ifelse(df.sample['病理类型']=='单纯型','Pure','Complex'))
attribute_names = c('TNM','pTNMs','subtype','smoke','survival_level')

filename = paste0("~/workstation/MetabSubtype/tasks/MultiOmics/results/20240930_essay_figures/Immune/",'lipid_attributes','.pdf')
pdf(filename,5,5)
for (attribute_name in attribute_names){
  p = plot_stacked_bar_percentage(stacked.sample,'lipid_cluster',attribute_name)
  print(p)
}
dev.off()

filename = paste0("~/workstation/MetabSubtype/tasks/MultiOmics/results/20240930_essay_figures/Immune/",'metab_attributes','.pdf')
  pdf(filename)
for (attribute_name in attribute_names){
  p = plot_stacked_bar_percentage(stacked.sample,'metab_cluster',attribute_name)
  print(p)
}
dev.off()



```

```{r}
df= df.sample
cluster_col = 'lipid_cluster'
attribute_col = 'smoke'
 df_summary <- df %>%
    group_by(!!sym(cluster_col), !!sym(attribute_col)) %>%
    tally() %>%
    group_by(!!sym(cluster_col)) %>%
    mutate(percentage = n / sum(n) * 100)
```

```{r}
df = df [,2:ncol(df)]
 df_summary <- df %>%
    group_by(lipid_cluster, smoke) %>%
    tally() %>%
    group_by(!!sym(cluster_col)) %>%
    mutate(percentage = n / sum(n) * 100)
```
